INSERT INTO registered_flow (PROJECT_ID, FLOW_NAME, CLASS_INFO_JSON) VALUES (1, 'Flow To add New Veterinarian', '[{"className": "Pet", "methods": ["getPetName()"]}]');
INSERT INTO registered_flow (PROJECT_ID, FLOW_NAME, CLASS_INFO_JSON) VALUES (1, 'Flow To retrieve a Pet', '[{"className": "Person", "methods": ["getAge()"]}]');
INSERT INTO registered_flow (PROJECT_ID, FLOW_NAME, CLASS_INFO_JSON) VALUES (1, 'Flow to update  a Pet', '[{"className": "Person", "methods": ["getAge()"]}]');

INSERT INTO project (PROJECT_ID, PROJECT_NAME, CLASS_INFO_JSON) VALUES (1, 'ProjectName1', '[{"className": "Pet", "methods": ["getPetName()", "setAge()"]}]');
INSERT INTO project (PROJECT_ID, PROJECT_NAME, CLASS_INFO_JSON) VALUES (2, 'ProjectName2', '[{"className": "Person", "methods": ["getAge()", "setAge()"]}]');

INSERT INTO documentation_template (type, template_system, template_user)
VALUES
('TECHNICAL',
 'Channel the experience and knowledge of a senior developer and technical writer. Given the code or technical topic below, provide a detailed, comprehensive, and technically accurate explanation, walkthrough, or documentation, as if explaining to a fellow developer. Make sure to address nuances, best practices, and potential pitfalls.',
 'Given the code provided below, generate a concise yet comprehensive documentation based on the following topic model:\n\nFunctionality Overview: A brief description of what the code does .\nUsage: How to use or implement the code.\nParameters and Returns: Details about the input parameters and return values.\n\n');

INSERT INTO documentation_template (type, template_system, template_user)
VALUES
('BUSINESS',
 'Channel the experience and knowledge of a senior business analyst with strong technical knowledge. Given the business or technical topic below, provide a detailed, comprehensive, and technically accurate explanation, walkthrough, or documentation, as if explaining to a fellow business analyst. Make sure to address nuances, best practices, and potential pitfalls.',
 'Abstract: Generate a straightforward business document focusing on the core essentials of business flow and value and DON''T include any code. This template should serve as a comprehensive guide for stakeholders of all levels.\n\nRequirements:\n\nBusiness Overview: A concise introduction to the business, its primary objectives, and operations.\n\nBusiness Flow: Description of core processes, their interactions, and significance in layman''s terms.\n\nBusiness Value: Breakdown of the direct and indirect benefits each process brings to the enterprise.\n\nRisks and Challenges: Identification of potential hurdles in the business flow and strategies to overcome them.\n\nthe code:\n');

INSERT INTO documentation_template (type, template_system, template_user)
VALUES
('CODE',
 'Channel the experience and knowledge of a senior developer and technical writer. Given the code or technical topic below, provide a detailed, comprehensive, and technically accurate explanation, walkthrough, or documentation, as if explaining to a fellow developer. Make sure to address nuances, best practices, and potential pitfalls.',
  'Can you analyze the code and suggest improvements related to best practices, efficiency, error handling, and code readability? Additionally, if you see opportunities to implement advanced features or design patterns, please recommend them. I''m particularly interested in ensuring that the response is clear, follows best practices for coding, is easily consumable by clients, and provides meaningful information both in successful and error scenarios.'  );

INSERT INTO documentation_template (type, template_user, template_system)
VALUES
('ARCHITECTURE',
 'You are a software architect. Can you analyze the given requirements and suggest a proposed architecture adhering to the prompt above? I''m particularly interested in ensuring that the design is clear, scalable, follows best practices for software architecture, and can be easily implemented by developers. Additionally, please make sure that the architecture is modular and adheres to clean architecture principles.',
 'Given a list of features for a Java Spring Boot application, please provide a design suggestion outlining: The number of services/repositories to create. It should be a service oriented architecture [not a microservice or monolith one]. Grouping of these services should be by bounded context. Generate a directory tree structure for a Java-based web application using Maven. A recommended project architecture, including package names and class names.Do this for all the services/repositories.  Ensure the design adheres to clean architecture principles.  Please consider the features listed below:' );

INSERT INTO documentation_template (type, template_user, template_system)
VALUES
('PO',
 'You are an seniour  product owner. The product you oversee has a dynamic user base. Feedback flows in from varied sources, and the competition is consistently innovating. The development team awaits your guidance for the upcoming product update based on the market and user demands.',
 'Given the present state of your product:' || CHAR(10) ||
 '1. Examine the list of both developed and pending features.' || CHAR(10) ||
 '2. Considering market dynamics, user input, recent tech developments, and the product''s trajectory:' || CHAR(10) ||
 '   - Identify which features should be fast-tracked for the upcoming release.' || CHAR(10) ||
 '   - Propose refinements or alterations to current features to boost user experience or fulfill newfound requirements.' || CHAR(10) ||
 '   - Conceive novel features or concepts that might be absent from the list but could be invaluable in the prevailing context.' || CHAR(10) ||
 '3. Substantiate your decisions by elucidating the potential upsides, hazards, and the foreseen impact on users and the enterprise. Please consider the features listed below:' );

INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Initial setup', 1, 'Backend Environment setup', 'As a prerequisite for starting to develop all features, we need to do the initial project setup. This requires: creating a Java project, setting up all the technologies and tools that we are going to use SpringBoot, Swagger, liquibase, DB connection and creating dummy data.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Initial setup', 2, 'Frontend Setup', 'As a prerequisite for stating development for all feature, we need to add initial project setup. This requires: creating React project, setting up axios configuration, also will be needed library for all components that will be reused. Initial setup requires also MUI setup for creating components. Setting up all internal CI/CD lint, unit testing, formaters, react router and rxjs', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Initial setup', 3, 'Design (UX/UI) Setup', 'As a prerequisite we need to check which features / parts of the current design proposal can be re-used, needs to be changed or added and how will they impact the technical and business constraints as well as the whole user journey.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Header', 4, 'Search engine by employee name', 'As a user I want to have search engine option where I will be able to search for employees by their names So that I can easily access their profile pages.', 'Header visible on every page.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Header', 5, 'Light/Dark mode option', 'As a user I want to be able to switch between light and dark modes in the application So that I can customize the visual appearance for better readability and reduced eye strain based on my preference and lighting conditions.', 'Header visible on every page.', 'Comment (25.08.2023): PO decided to remove from Next to Last.');
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Header', 6, 'Notification field (ring icon)', 'As a user I want to have a notification field with a ring icon prominently displayed and option to dismiss after I’ve seen the notification So that I can quickly identify and access any new notifications or updates related to my assigned candidates.', 'Header visible on every page; post mvp e-mail notification also.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Header', 7, 'User profile', 'As a user I want to have access to a user profile section in the application So that I can view and manage my profile information, as well as easily sign out when needed.', 'Header visible on every page; drop down list with My profile; Sign out (for MVP only design without actions).', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Actions field', 9, 'Set reminders', 'As a user I want to have the option to set reminders as part of dropdown list of the Actions field and when I click on the ''Set reminders'' I want to see the following fields: To (select from Active Directory), Title, Remind me to, Reminder date and time, and buttons: Cancel and Send So that I can easily manage my coaching responsibilities and don''t miss important reminders.', 'Actions field visible on every page; reminders visible only for the career coach and shown only on the app as part of the: Dashboard, Candidate Profile, as mvp (e-mail post mvp)', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Actions field', 10, 'Add project rotation flag', 'As a user I want to have the option to add project rotation flag as part of dropdown list of the Actions field, that will set the project rotation flag to green, and I want to see the following field when I click on ''Add project rotation flag'': To (select from Active Directory), Comment, and buttons: Add and Cancel So that I can easily manage my coaching responsibilities and take the following actions for the wanted project rotation.', 'Actions field visible on every page; updated status (as done) should be taken from History page ''Project history''', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Actions field', 11, 'Promotion nomination', 'As a user I want to have the option to nominate my candidates for promotion as part of dropdown list of the Actions field and when I click on ''Promotion nomination'' I want to see checkbox list of all my coachees and button to save and cancel So that I can easily manage my coaching responsibilities and have better visibility of promoted coachees on the Dashboard (Promotion candidates menu).', 'Actions field visible on every page;', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Actions field', 12, 'Set happiness level', 'As a user I want to have the option to Set happiness level of my coachees as a part of dropdown list of the Actions field and when I click on ''Set happiness level'' I want to see To (list of each coachee (Active Directory)) and slider so that I can set their happiness level after every session with them.', 'Actions field visible on every page; Once the user set the values on the slider, the application should save these values and display them on the coachee''s profile; and display face icon on the dashboard ( 0 - 2.5 represented by a sad red face icon; 2.5 - 7.5 represented by a neutral yellow face icon; 7.5 - 10 represented by a happy green face icon)', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Dashboard', 13, 'Tab options (career coach, compensation reviewer, line manager)', 'As a user I want to see different tab options (Career Coach, Compensation Reviewer, Line Manager) based on the roles I am assigned So that I can access and interact with information that is relevant to my specific responsibilities.', 'one career coach can be also a line manager and compensation reviewer, so depending on what kind of roles he has – that kind of info should be visible on the dashboard.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Dashboard', 14, 'Dummy Quote Field', 'As a user, I want to see quote field modal So that I can read one motivational quote on every page.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Dashboard', 15, 'Quote slide bar', 'As a user, when I log in the application I want to see a circular modal on the right side of the screen that will show inspirational quotes and I want the quotes to change automatically So that I can read a new quote every day visible on every page.', 'for MVP we only want design for the slide bar', 'Use https://jsoup.org/ for scraping the inspirational quotes Use a free inspirational quotes website. Example: https://www.forbes.com/sites/kevinkruse/2013/05/28/inspirational-quotes/?sh=8ce225e6c7ac');
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Dashboard', 16, 'Sorting option', 'As a user I want to have the ability to sort and organize my list of coachees based on different criteria, sort by name, and sort by role/position So that I can quickly identify my assigned coachees and manage my coaching responsibilities effectively.', 'for MVP they only want sort by name, sort by role/position', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Dashboard', 17, 'Return a list of all coachees', 'As a user I want to have the ability to retrieve a complete and organized list of all coachees assigned to me, So that I can efficiently manage and sort them appropriately if needed.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Dashboard', 18, 'Front look of coachees profile', 'As a user I want to see the shortcut of the coachee''s profiles with the name of the coachee, progress level and icons for happiness level, last meeting date, badge for promotion, project rotation, current project So that I can have a snapshot of their progress, important milestones, and relevant details at a glance.', 'icons should have different colors - post MVP (for ex. current project - if he is on bench - grey color, if he is on project green color; project rotation - green color if coachee requested project rotation; promotion – green color - requested promotion; meeting date – red if there is upcoming meeting during the day, green if there is upcoming meeting but it’s not it the current day)', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Dashboard', 19, 'Reminders menu', 'As a user, I want a dedicated "Reminder Menu" where will be displayed my notes related to my coaching responsibilities, also to see upcoming meetings, and access to them (add/edit) So that I can maintain organized and easily accessible reminders to enhance my coaching interactions.', '+ button which will take you to a separate page.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 21, 'Create Profile Page', 'As a user after selecting specific candidate/coachee from the dashboard page I want to be redirected to the Candidate Profile Page So that I can view candidate''s basic information (Name, Image, Job Position and Grade).Later to be added Compensation and Line Manager.', 'This section with the employee''s basic information shall be visible on:Notes, Templates and History Page - the action menu visible on the Profile Page and covered on the Dashboard Page is not in the scope of this requirement', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 22, 'View/Manage reminders related to selected Candidate', 'As a user, while on the Candidate Profile Page I want to be able to see reminders related to meetings with the selected candidate as well as create new reminders So that I can easily keep track of scheduled activities.', 'Same component as on the Dashboard Page, just the reminders here will be filtered by the selected Coachee.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 23, 'View list of Skills', 'As a user, while on the Candidate Profile Page I want to be able to see a list of all employee''s Skills So that I have better view of the Coachee’s competences.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 24, 'Manage the list of Skills', 'As a user, while on the Skills section of the Candidate Profile’s Page I want to able to manage the Skill’s list So that I can assign new skills from a prepopulate list of skills as well as remove existing skill from the list and date for the acquired skill. The skills shall be categorised into:Soft Skills, Client and Commercial/Technical/Leadership', 'No Mockup for this feature.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 25, 'View list of Project Preferences', 'As a user, while on the Candidate Profile Page I want to be able to see a list of the employee''s Project Preferences, So that I have better visibility and understanding of his career path and potential fits.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 26, 'Manage list of Project Preferences', 'As a user, while on the Candidate Profile’s Page I want to able to manage the Project Preferences list So that I can assign new project preferences from a prepopulated list of projects as well as remove existing project preference from the list and add the reason for adding/removing the project preference.', 'No Mockup for this feature.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 27, 'View List of Technologies', 'As a user, while on the Candidate Profile Page I want to be able to see a list of the employee''s Technologies So that I have better visibility and understanding of his technical expertise and potential fits.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 28, 'Manage list of Technologies', 'As a user, while on the Candidate Profile’s Page I want to able to manage the Technologies list So that I can assign new technologies from a prepopulated list of technologies as well as remove existing technology from the list.', 'No Mockup for this feature.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 29, 'View List of Technology Preferences', 'As a user, while on the Candidate Profile Page I want to be able to see a list of the employee''s Technology Preferences, So that I have better understanding of his career path.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 30, 'Manage List of Technology Preferences', 'As a user, while on the Technology Preferences section of the Candidate Profile’s Page, I want to able to manage the list with Technology Preferences So that I can add and remove technology preferences from a prepopulated list.', 'No Mockup for this feature.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 31, 'Couchee''s happiness level', 'As a user, while on the Candidate Profile Page I want to be able to see a graph with candidate happiness level (calculated from the Happiness level set on the Action menu) per selected time span (1, 2,3 ..years) So that I have better understanding of the Coachee’s career path', 'For the calculations of Happiness levels, it was agreed that initially AI won’t be used for this phase. Later we would use existing information from the Candidate Profile:Employee engagement, Employee performance.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 32, 'Couchee''s project allocation/bench', 'As a user, while on the Candidate Profile Page I want to be able to see a graph with candidate project allocation/bench ratio per selected time span (1, 2,3 ..years) So that I have better understanding of the Coachee’s career path.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Candidate Profile Page', 33, 'Left Menu navigation', 'As a user, while on the Candidate Profile Page I want to be able to see a left menu So that I shall be able to navigate to Notes Page, Growth Plan Page, Career Map, Templates Page and Project History and manage notes, to see growth plan, templates, history of candidate respectively.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 34, 'Open Notes Page', 'As a user, after navigating to the Notes page from the Profile Page left menu, I want to see a list with all Review Cycle’s that I’ve already created So that I can easily track history of candidate''s career path.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 35, 'View list of Private and Shared Notes', 'As a user, while on the Notes Page, I want to see a list with all Private and Shared Notes in two separate tabs So that I can have access into the activities, discussions with the Coachee.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 36, 'Search Note', 'As a user, while on the Notes Page I want to be able to search for a specific Note by entering part of the Note Title or Note Description So that I can easily access specific Note.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 37, 'Create New Review Cycle', 'As a user, while on the Notes Page I want to be able to create new Review Cycle and add information like Title So that I can better plan communication and activities with the Coachee', 'Date To/Date From won''t be editable, instead we will have predefined set of periods. There is a possibility to r', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 38, 'Create New Note', 'As a user, while on the Notes Page I want to be able to create a new Note and add information like Title, Text and assign the Note to a specific Review Cycle from a prepopulated list or share it with others So that I can better track activities and track discussed issues with the Coachee.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 39, 'Edit Existing Note', 'As a user, while on the Notes Page I want to be able to Edit existing Note and add modify information like Title, Text and assign the Note to a specific Review Cycle from a prepopulated list or share it with others So that I can better track activities and track discussed issues with the Coachee.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 40, 'Move Existing Note', 'As a user, while on the Notes Page I want to be able to move an existing note from one Review Cycle to another from a prepopulated list So that I can better track activities and track discussed issues with the Coachee.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 41, 'Share Existing Note', 'As a user, while on the Notes Page I want to be able to Share existing Note with others So that others are informed about some of the activities and discussions I have with the Coachee.', 'In the first phase we can disable the share button and add a checkbox. We don''t have mockups for this feature!', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 42, 'Delete Existing Note', 'As a user while on the Notes Page I want to be able to Delete existing Note So that I won’t keep unnecessary information.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 43, 'View Feedbacks per Review Cycle', 'As a user, while on the Notes Page I want to be able to see a Feedback section, from where I can view all past requested feedbacks for given Review Cycle So that I can better track history of the Coachee’s progress.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 44, 'Search for specific Feedback', 'As a user, while on the Feedback section on the Note Page I want to be able to search for specific Feedback by Name, Description, Provided By So that I can easily find specific feedback of interest.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Notes Page', 45, 'Ask For Feedback', 'As a user, while on the Feedback section on the Note Page I want to be able to request for feedback So that I can help coachee better evaluate himself and make progress in his career. The feedback will be categorized by', 'Since the career coach will be the ONLY user of this app in the first phase, we won''t have a possibility to actually send/receive feedback from someone(use dummy data). In the later phase we will include receiving feedback from someone outside the organization. No Mockup for the feedback screen.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 46, 'Growth Plan - Layout', 'As a user in the Growth Plan page I want to have a title ‘GROWTH PLAN’ and one button ‘Create new plan’ So that I can easily notice that I am in the growth plan tab and I can easily create new growth plans for my coachees.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 47, 'Growth Plan - Layout', 'As a user when I am in the Growth Plan page I want the screen to be divided in two parts. On the left part of the screen I want to see all the growth plans that I have created for one coachee and on the right part I want to see the content of a particular plan So that I can easily see what is the current or past growth plan for my coachee and what action points do I have for it.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 48, 'Create new Growth Plan', 'As a user when I am in the Growth Plan page I want on click on the button ‘Create new plan’ a new pop up window to be opened with the following fields: Title, From, To, Current Grade, Next Grade, Save and Cancel So that I can create a new growth plan.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 49, 'Display of created Growth Plans', 'As a user when I have created a few growth plans for one coachee I want to see them listed by date of creation (the most recent ones to be displayed on top of the list) in the left part of the Growth Plan screen So that I can see all of the details entered in them.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 50, 'Display of Selected Growth Plan', 'As a user when I have created a few growth plans for one coachee I want when I select one of them (by clicking on it), the coloring of the text to change from black to red So that it will be more obvious which one is selected and for which one we are seeing more details about.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 51, 'Hoover button for the Growth plan', 'As a user when I have created a growth plan for one coachee that is displayed on the left part of the screen, I want right next to it to have a hover button (3 dots placed vertically), So that I can perform different actions on the growth plan.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 52, 'Hoover button for the Growth plan - clickable options', 'As a user when I have selected one growth plan from the list and then hoover over the button (3 dots placed vertically) right next to each plan, I want to see the following clickable options listed: EDIT PLAN and DELETE PLAN, So that I can edit or delete it if needed.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 52, 'Hoover button for the Growth plan - clickable options', 'As a user when I have selected one growth plan from the list and then hoover over the button (3 dots placed vertically) right next to each plan, I want to see the following clickable options listed: EDIT PLAN and DELETE PLAN, So that I can edit or delete it if needed.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 53, 'Growth Plan - Edit option', 'As a user when I have one growth plan selected, I want on click on ‘EDIT PLAN’ (from the hover button) a new pop up window with the following fields: Title, From, To, Current grade, Next grade, Save and Cancel to be opened for editing the plan, So that I can make changes or correct unintentional mistakes.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 54, 'Growth Plan - Delete option', 'As a user when I have one growth plan selected, I want on click on ‘DELETE PLAN’ (from the hoover button) a new pop up window to be opened with the following question: ‘Are you sure that you want to delete the Growth Plan (Title)?’ and the options ‘Yes’ or ‘No’, So that I can delete the plan if it is no longer needed', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 55, 'Detailed View', 'As a user when I click on one of the created growth plans for which I don’t have action points, I want on the right side of the screen to be displayed the name of the growth plan, the date and time when the plan was created and a hover button (3 dots placed vertically), So that I can see more details about the growth plan or perform more actions.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 56, 'Hoover button - Add new Action Point', 'As a user when I hover over the button right next to the date and time of the creation of the plan, I want to see the following clickable option: ‘Add new action point’, So that I can add more action points when needed.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 57, 'Save new action point', 'As a user once I have entered and clicked to save the action point, I want it saved in the following format: check box field, to see a number in front of the text box field that will indicate how many action points do I have (1,2,3…), in the right upper corner of the box to have a hover button (3 dots placed vertically) and a button in the lower right corner, So that I will know how many action points I have for this Growth Plan and to be able to perform different actions on the AC itself.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 58, 'Action Points - not completed', 'As a user when I have added and saved a new action point to a growth plan, I want the numbering of all of the action points to be displayed with red color, So that I will be aware that there are action points that are still active and are not completed/fulfilled by the coachee.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 59, 'Action Points - completed', 'As a user when I have an action point that is completed by the coachee, I want when I click on the check box field, the color of the title and the numbering to be changed to green, So that I will be aware that those points are completed.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 60, 'Hoover button - Action Point', 'As a user when I hover over the 3 dots button in a particular Action Point then, I want to see the following clickable options displayed as a list: Edit, Delete and Move, So that I can perform different actions on the action points.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 61, 'Action Point - Edit option', 'As a user when I hover over the button (3 dots placed vertically) in the text box field and I click on ‘Edit’ then, I want the content in the action point to become editable, So that I can edit the text or change some unintentional mistakes.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 62, 'Action Point - Delete option', 'As a user when I hover over the button (3 dots placed vertically) and I click on ‘Delete’ then, I want the following question to be displayed ‘Are you sure that you want to delete the Action Point (Title)?’ and the options ‘Yes’ or ‘No’, So that I can I can delete the plan if it is no longer needed.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 63, 'Action Point - Move option', 'As a user when I hover over the button (3 dots placed vertically) and I click on ‘Move’ then, I want with dragging the action point to be able to move it up or down, So that I can change its priority.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Growth Plan', 64, 'Open Action Point in a bigger screen', 'As a user when I click on the button in the lower right corner of a saved action point, I want the content of the action point to be displayed in a bigger pop up screen, So that I can read the whole text placed In it.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Templates Page', 65, 'Display all the Templates', 'As a user when I click on the "Templates" tab on the left menu, I want to see all the Templates that I''ve created for that Coachee (in the templates part of the screen, below the Coachee profile information) listed by date of creation (the most recent ones to be displayed on top of the list)', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Templates Page', 66, 'Create New Template', 'As a user when I click on the button named "Create new template", I want to see a new form open where I can create (write) a new template with the following fields: 1. Name of the template, 2. Template content', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Templates Page', 67, 'Search Templates', 'As a user when I click on the "Templates" tab on the left menu, I want to see a search bar next to the "Create new template" button and I want to be able to search templates by name', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Templates Page', 68, 'Show template details', 'As a user when I have selected template from the right panel, I want to see all of the details entered in them.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Templates Page', 69, 'Edit and Delete a Template', 'As a user when I have selected one template from the list and then hover over the button (3 dots placed vertically), I want to see the following clickable options listed: EDIT TEMPLATE and DELETE TEMPLATE so that I can edit or delete it if needed.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('History Page', 70, 'View of Project History', 'As a user when I click on the "History" tab on the left menu, I want to see all the projects the coachee has worked on before (in a vertical list) and I need to be able to see the following information for every project entry: 1. Project Name "Flying Tunder Cats App (Current Project)" - If this is my current project, 2. The role of the coachee in the project "Business Analyst", 3. Date when the project/bench started "01.02.2023".', 'The list will have predetermined sorting by date', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('History Page', 71, 'View of Promotion Nomination Request History', 'As a user when I click on the "History" tab on the left menu I want  to see all the promotion nomination requests that the coachee has made and I need to be able to see the following information for every promotion nomination request 1. Project Name "The Upgrade" 2. The grade the promotion nomination request was created "Engineer" 3. Date of the promotion nomination request "01.07.2023"', '*Note: The list will have predetermined sorting by date *Note: No mockup/UX Design for "Promotion Nomination Request History"', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('History Page', 72, 'View of Project Rotation Requests History', 'As a user when I click on the "History" tab on the left menu I want to see all the project rotation requests that the coachee has made and I need to be able to see the following information for every project rotation request 1. Project Name "The Old Project" 2. The role of the coachee in the project "Business Analyst" 3. Date of the project rotation request "01.07.2023"', '*Note: The list will have predetermined sorting by date *Note: No mockup/UX Design for "Project Rotation Requests History"', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Career Map Service Setup', 73, 'Career Map service Setup BE', 'As a prerequisite for starting to develop feature requirements for career map, we need to do service setup. This requires:  setting up all the technologies and tools that we are going to use (Java, SpringBoot...), DB connection and creating dummy data.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Career Map Service Setup', 74, 'Career Map service Setup FE', 'As a prerequisite for starting develop feature for career path service setup we will need to do initial setup', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Career Map', 75, 'List of Discipline career paths', 'As a Coach I want to have access to a visual presentation that displays career paths associated with various disciplines So that I can gain insights into different professions and make informed decisions about future career choices.', '*Note: Visual presentation of all Discipline''s career paths listed one under the other Career Map is a new field on the left main Menu, the same as other main function (Profile, Notes, Action Points, Templates, History)', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Career Map', 76, 'Presentment of Job Roles for each Discipline', 'As a Coach I want to access a comprehensive presentation of job roles within different disciplines, ordered by seniority levels, So that I can understand the progression paths and career growth opportunities available', '*Note: Job Roles seniority levels within Disciplines, starting with the most junior ones and finishing with the most senior ones.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Career Map', 77, 'Visual presentation possible career opportunity', 'As a Coach I want to access a navigation course that presents the current job role of the coachee, as well as the potential next career opportunities within the discipline and other related disciplines, So that I can be aware of possibilities for growth and advancement', '*Note: Visual presentment of current Job Role and next possible career opportunities within the discipline and other disciplines', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Career Map', 78, 'Accessing Key Career Information', 'As a Coach I want to have access to an information panel that provides a quick view of essential details related to the coachee''s current job role, as well as the potential next career opportunities So that I can stay informed about career trajectory', '*Note: Information panel - Quick view of most important details related to the Job Role, such as current Job Overview and Next Career Opportunities', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Chat Bot Setup', 79, 'Technical setup - Backend', 'As a prerequisite for starting develop feature for chat bot service setup we will need installment of openAI module.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Chat Bot Setup', 80, 'Technical setup - Frontend', 'As a prerequisite for starting develop feature for chat bot service setup we will need installment of openAI module.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Chat Bot', 81, 'KT Session', 'As a prerequisite for starting develop chat bot feature will need to do some KTs, documentation reading.', NULL, NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Chat Bot', 82, 'Enhancing Communication with Natural Language Processing (NLP)', 'As a Coach I expect the chatbot to comprehensively understand and interpret my natural language input, including context, intent, and sentiment So that more efficient and meaningful interactions can be enabled', '*Note: Comprehend and interpret natural language input from coaches, understanding context, intent, and sentiment', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Chat Bot', 83, 'Seamless Conversations with Contextual Awareness', 'As a Coach I want the chatbot to exhibit contextual awareness during conversations and to maintain context from previous interactions So that can provide responses and follow-up questions that are relevant to ongoing discussion', '*Note: Maintain context throughout the conversation, enabling it to provide relevant responses and follow-up questions based on previous interactions.', NULL);
INSERT INTO Requirements (Category, SUB_ID, Title, Description, Notes, Comments) VALUES
('Chat Bot', 84, 'Insights and Analytics', 'As a Coach I want the chatbot to provide insights and analytics about the questions I ask related to the coachee. I expect the chatbot to analyze candidate details and offer data-driven insights to help me make informed decisions.', '*Note: Provide insights and analytics about asked questions related to candidates', NULL);